TOGGLE_FULL_SCREEN_SHORTCUT_TEXT = "Ctrl+Alt+F"
TOGGLE_ACTIVITY_DOCK_SHORTCUT_TEXT = "Ctrl+Alt+D"
EXIT_FULL_SCREEN_SHORTCUT_TEXT = "Esc"

OPEN_PROJECT_SHORTCUT_TEXT = "Ctrl+O"
SHOW_ALL_SHORTCUTS_SHORTCUT_TEXT = "Ctrl+Shift+S"
OPEN_PREFERENCES_SHORTCUT_TEXT = "Ctrl+Shift+P"
SAVE_PROJECT_SHORTCUT_TEXT = "Ctrl+S"
CLOSE_PROJECT_SHORTCUT_TEXT = "Ctrl+Q"
